name: Latest blog post workflow
on:
  # schedule: # Run workflow automatically
  #  - cron: '30 8 * * *' # Runs every day on 8:30 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://shriekdj.hashnode.dev/rss.xml"
          template: "<tr><td>$title</td><td><a href='$url' target='_blank'>$url</a></td></tr>"
